// <auto-generated />
using System;
using Carreras.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carreras.Migrations
{
    [DbContext(typeof(CarrerasContext))]
    partial class CarrerasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("CarreraParticipante", b =>
                {
                    b.Property<int>("CarrerasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarrerasId", "ParticipantesId");

                    b.HasIndex("ParticipantesId");

                    b.ToTable("CarreraParticipante");
                });

            modelBuilder.Entity("Carreras.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<float>("DistanciaEnMetros")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroCarrera")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("Carreras.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Club")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dorsal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PosicionGeneral")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TiempoOficial")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Participante");
                });

            modelBuilder.Entity("CarreraParticipante", b =>
                {
                    b.HasOne("Carreras.Models.Carrera", null)
                        .WithMany()
                        .HasForeignKey("CarrerasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carreras.Models.Participante", null)
                        .WithMany()
                        .HasForeignKey("ParticipantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
